name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes
         

    
      - name: Example
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: RP-developer-01
          repo: shopPhp
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: RP-developer-01/shopPhp
          
      - name: Example (pdf output)
        uses: lowlighter/metrics@latest
        with:
          template: markdown
          markdown_cache: .cache
          filename: metrics.markdown.pdf
          markdown: >-
            https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.pdf.md
          config_output: markdown-pdf
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          plugin_isocalendar: yes
          config_twemoji: yes
          config_padding: 5%
          token: ${{ secrets.METRICS_TOKEN }}

    
