- name: Featured star list
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.starlists.svg
    token: NOT_NEEDED
    base: ""
    plugin_starlists: yes
    plugin_starlists_limit_repositories: 2
    plugin_starlists_only: TC39
  test:
    timeout: 1800000

- name: Featured star list languages
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.starlists.languages.svg
    token: NOT_NEEDED
    base: ""
    plugin_starlists: yes
    plugin_starlists_languages: yes
    plugin_starlists_limit_languages: 8
    plugin_starlists_limit_repositories: 0
    plugin_starlists_only: Awesome
  test:
    timeout: 1800000
    
- name: Featured star list languages
  uses: lowlighter/metrics@latest
  with:
    filename: metrics.plugin.starlists.languages.svg
    token: NOT_NEEDED
    base: ""
    plugin_starlists: yes
    plugin_starlists_languages: yes
    plugin_starlists_limit_languages: 8
    plugin_starlists_limit_repositories: 0
    plugin_starlists_only: Awesome
    
- name: Example
  uses: lowlighter/metrics@latest
  with:
    template: repository
    filename: metrics.repository.svg
    token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
    user: lowlighter
    repo: metrics
    plugin_lines: yes
    plugin_followup: yes
    plugin_projects: yes
    plugin_projects_repositories: lowlighter/metrics/projects/1

